config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :camps do
    resources :reviews
  end

  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  validates :name, uniqueness:true, presence: true, length: { minimum: 3 }
  validates :address, uniqueness: true, presence: true

  has_many :reviews
  has_many :users, through: :reviews

  geocoded_by :full_address
  after_validation :geocode, if: (:address_changed? || :city_changed? || :province_changed?)

  def full_address
    "#{address} #{city} #{province}"
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :camp
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, presence: true, length: { minimum: 5 }, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true, presence: true
  validates :username, uniqueness: true, presence: true

  has_many :reviews
  has_many :camps, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private  
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    @camps = if params[:search]
      Camp.near(params[:search], 50, units: :km)
    elsif params[:latitude] && params[:longitude]
      Camp.near([params[:latitude], params[:longitude]], 50, units: :km)
    else
      Camp.all
    end

    respond_to do |format|
      format.html
      format.js
    end 
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
    if current_user
      @review = @camp.reviews.build
    end
    @nearby_camps = @camp.nearbys(30, units: :km)
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :address, :city, :province, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_camp
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:edit, :create, :update, :destroy]

  def show
  end

  def edit
  end

  def create
    @review = @camp.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to camp_path(@camp), notice: 'Review created successfully.'
    else
      render 'camps/show'
    end
  end

  def update
    if @review.update(review_params)
      redirect_to @camp, notice: 'Review was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to camps_url(@camp), notice: 'Review was successfully deleted.'
  end

  private
  def review_params
    params.require(:review).permit(:comment, :camp_id)
  end

  def load_camp
    @camp = Camp.find(params[:camp_id])
  end

  def set_review 
    @review = Review.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed. Please try again.'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username, :bio)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/camps/_camp.html.erb
<tr>
  <td><%= link_to camp.name, camp %></td>
  <td><%= camp.full_address %></td>
  <td><%= camp.description %></td>
</tr>

app/views/camps/_form.html.erb
<%= form_for(@camp) do |f| %>
  <% if @camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% @camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/camps/_review.html.erb
<% @camp.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <% if review.user != nil %>
      <em>by <%= review.user.username %></em>
      Added on: <%= review.created_at %>
    <% end %>
    <% if current_user && (current_user.id == review.user_id) %>
      <%= link_to 'Edit',  edit_camp_review_path(review.camp_id, review.user_id) %>
    <% end %>
  </p>
<% end %>

app/views/camps/edit.html.erb
<h1>Editing Camp</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<h1>Campgrounds</h1>

<section style="clear:both">
  <button id="current_location">Find Campgrounds within 50km near me</button>
</section>

<section style="clear:both">
  <%= form_tag camps_path, method: :get do %>
    <%= label_tag :search, 'Find campgrounds within 50km nearby:' %>
    <%= text_field_tag :search, params[:search], placeholder: "Address" %>
    <%= submit_tag "Search" %>
  <% end %>
</section>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody id="camps">
    <%= render @camps %>
  </tbody>
</table>

<br>

<%= link_to 'Add a campground', new_camp_path %>

app/views/camps/index.js.erb
$('#camps').html('<%= j(render @camps) %>');

app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form' %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<h1><%= @camp.name %> Info</h1>

<div class="info">
  <p>Location: <%= @camp.full_address %></p>
  <p>Description: <%= @camp.description %></p>
</div>

<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>

<h3>Reviews</h3>

<%= render 'review' %>

<% if current_user %>
  <h4>New Review</h4>
  
  <%= render 'reviews/form' %>

<% else %>
    <p>Please <%= link_to "login", new_session_path %> to add a review.</p>
<% end %>

<div id="map-canvas" data-latitude="<%= @camp.latitude.to_f %>" data-longitude="<%= @camp.longitude.to_f %>"></div>


<% if @nearby_camps.any? %>
  <h2>Nearby Campgrounds within 30km</h2>
  <ul>
    <% @nearby_camps.each do |nc| %>
      <li><%= nc.name %>, <%= nc.distance %> kms</li>
    <% end %>
  </ul>
<% end %>

<%= javascript_tag do %>
  window.nearbys = <%= raw @nearby_camps.map { |nc|
    {latitude: nc.latitude, longitude: nc.longitude }}.to_json %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Camp Trip</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_maps_api}" %>
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Camp Trip", root_path %></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
        
          <% if current_user %>
            <li class="has-dropdown">
              <a href="#"><%= current_user.username %></a>
              <ul class="dropdown">
                <li><%= link_to "My profile", user_path(current_user.id) %></li>
                <li><%= link_to "Logout", :logout, method: :post %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Register", new_user_path %></li>
            <li><%= link_to "Login", :login %></li>
          <% end %>

        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <li><%= link_to "Campgrounds", camps_path %></li>
          <li><%= link_to "Campers", users_path %></li>
        </ul>
      </section>
    </nav>


    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>

    <%= yield %>

  </body>

</html>

app/views/reviews/_form.html.erb
<%= form_for([@camp, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review for <%= @review.camp.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', camp_path(@camp) %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Campers Directory</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Become a Camper', new_user_path %>

app/views/users/new.html.erb
<h1>Become a Camper</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<% if current_user && current_user.id == @user.id %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Delete my account', @user, method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %> |
<% end %>
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Camp Trip</h1>

<p>Plan your camping trip!</p>